const { Characters } = require("../models");
const charactersdata = [
  {
    title: "Spider-Man (Peter Parker)",
    intelligence: "4/7",
    strength: "4/7",
    speed: "3/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "spider-man.webp",
  },
  {
    title: "Thor (Thor Odinson)",
    intelligence: "2/7",
    strength: "7/7",
    speed: "7/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "thor-img.webp",
  },
  {
    title: "Doctor Strange (Stephen Strange)",
    intelligence: "4/7",
    strength: "2/7",
    speed: "7/7",
    durability: "2/7",
    energy: "6/7",
    fighting_skills: "6/7",
    image: "doctor-strange.webp",
  },
  {
    title: "Deadpool (Wade Wilson)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "7/7",
    durability: "4/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "deadpool.webp",
  },
  {
    title: "Iron Man (Tony Stark)",
    intelligence: "6/7",
    strength: "6/7",
    speed: "5/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "iron-man.webp",
  },
  {
    title: "Wolverine (James Howlett)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "2/7",
    durability: "4/7",
    energy: "2/7",
    fighting_skills: "7/7",
    image: "wolverine.webp",
  },
  {
    title: "Hulk (Bruce Banner)",
    intelligence: "6/7",
    strength: "7/7",
    speed: "3/7",
    durability: "7/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "hulk.webp",
  },
  {
    title: "Captain America (Steve Rogers)",
    intelligence: "3/7",
    strength: "3/7",
    speed: "2/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "captain-america.webp",
  },
  {
    title: "Black Panther (T'Challa)",
    intelligence: "5/7",
    strength: "3/7",
    speed: "2/7",
    durability: "3/7",
    energy: "3/7",
    fighting_skills: "5/7",
    image: "black-panther.webp",
  },
  {
    title: "Scarlet Witch (Wanda Maximoff)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "2/7",
    durability: "2/7",
    energy: "6/7",
    fighting_skills: "3/7",
    image: "scarlet-witch.webp",
  },
  {
    title: "Black Widow (Natalia Romanova)",
    intelligence: "3/7",
    strength: "3/7",
    speed: "2/7",
    durability: "3/7",
    energy: "3/7",
    fighting_skills: "6/7",
    image: "black-widow.webp",
  },
  {
    title: "Groot",
    intelligence: "3/7",
    strength: "7/7",
    speed: "3/7",
    durability: "4/7",
    energy: "3/7",
    fighting_skills: "4/7",
    image: "groot.webp",
  },
  {
    title: "Ant-Man (Scott Lang)",
    intelligence: "4/7",
    strength: "5/7",
    speed: "3/7",
    durability: "5/7",
    energy: "3/7",
    fighting_skills: "4/7",
    image: "ant-man.webp",
  },
  {
    title: "Rocket (Rocket Raccoon)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "2/7",
    durability: "2/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "rocket-racoon.webp",
  },
  {
    title: "Star-Lord (Peter Quill)",
    intelligence: "4/7",
    strength: "3/7",
    speed: "2/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "star-lord.webp",
  },
  {
    title: "Ghost Rider (Johnny Blaze)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "3/7",
    durability: "5/7",
    energy: "4/7",
    fighting_skills: "2/7",
    image: "ghost-rider.webp",
  },
  {
    title: "Silver Surfer (Norrin Radd)",
    intelligence: "3/7",
    strength: "7/7",
    speed: "7/7",
    durability: "6/7",
    energy: "7/7",
    fighting_skills: "2/7",
    image: "silver-surfer.webp",
  },
  {
    title: "Punisher (Frank Castle)",
    intelligence: "3/7",
    strength: "3/7",
    speed: "2/7",
    durability: "2/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "punisher.webp",
  },
  {
    title: "Spider-Man (Miles Morales)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "3/7",
    durability: "3/7",
    energy: "2/7",
    fighting_skills: "3/7",
    image: "spider-man-miles-morales.webp",
  },
  {
    title: "Professor X (Charles Xavier)",
    intelligence: "5/7",
    strength: "2/7",
    speed: "2/7",
    durability: "2/7",
    energy: "5/7",
    fighting_skills: "3/7",
    image: "proffessor-x.webp",
  },
  {
    title: "Phoenix (Jean Grey)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "7/7",
    durability: "7/7",
    energy: "7/7",
    fighting_skills: "4/7",
    image: "phoenix.webp",
  },
  {
    title: "Gambit (Remy LeBeau)",
    intelligence: "2/7",
    strength: "2/7",
    speed: "2/7",
    durability: "2/7",
    energy: "2/7",
    fighting_skills: "4/7",
    image: "gambit.webp",
  },
  {
    title: "Nightcrawler (Kurt Wagner)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "7/7",
    durability: "2/7",
    energy: "1/7",
    fighting_skills: "3/7",
    image: "nightcrawler.webp",
  },
  {
    title: "Colossus (Piotr Rasputin)",
    intelligence: "2/7",
    strength: "6/7",
    speed: "2/7",
    durability: "6/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "colossus.webp",
  },
  {
    title: "Vision",
    intelligence: "4/7",
    strength: "5/7",
    speed: "3/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "3/7",
    image: "vision.webp",
  },
  {
    title: "Daredevil (Matt Murdock)",
    intelligence: "3/7",
    strength: "3/7",
    speed: "2/7",
    durability: "2/7",
    energy: "4/7",
    fighting_skills: "5/7",
    image: "daredevil.webp",
  },
  {
    title: "Ghost Rider (Robbie Reyes)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "7/7",
    durability: "5/7",
    energy: "3/7",
    fighting_skills: "4/7",
    image: "ghost-rider-robbie-reyes.webp",
  },
  {
    title: "Hawkeye (Clint Barton)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "2/7",
    durability: "2/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "hawkeye.webp",
  },
  {
    title: "Storm (Ororo Munroe)",
    intelligence: "2/7",
    strength: "2/7",
    speed: "3/7",
    durability: "2/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "storm.webp",
  },
  {
    title: "Winter Soldier (Bucky Barnes)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "2/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "winter-soldier.webp",
  },
  {
    title: "Moon Knight (Marc Spector)",
    intelligence: "2/7",
    strength: "3/7",
    speed: "2/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "moon-knight.webp",
  },
  {
    title: "Human Torch (Johnny Storm)",
    intelligence: "2/7",
    strength: "2/7",
    speed: "5/7",
    durability: "6/7",
    energy: "5/7",
    fighting_skills: "3/7",
    image: "human-torch.webp",
  },
  {
    title: "Blade (Eric Brooks)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "2/7",
    durability: "4/7",
    energy: "1/7",
    fighting_skills: "5/7",
    image: "blade.webp",
  },
  {
    title: "The Thing (Ben Grimm)",
    intelligence: "3/7",
    strength: "6/7",
    speed: "2/7",
    durability: "6/7",
    energy: "1/7",
    fighting_skills: "5/7",
    image: "the-thing.webp",
  },
  {
    title: "Cable (Nathan Summers)",
    intelligence: "3/7",
    strength: "4/7",
    speed: "7/7",
    durability: "4/7",
    energy: "4/7",
    fighting_skills: "6/7",
    image: "cable.webp",
  },
  {
    title: "Agent Nick Fury)",
    intelligence: "3/7",
    strength: "3/7",
    speed: "2/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "agent-nick-fury.webp",
  },
  {
    title: "Captain Marvel (Carol Danvers)",
    intelligence: "3/7",
    strength: "5/7",
    speed: "5/7",
    durability: "6/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "captain-marvel.webp",
  },
  {
    title: "Nova (Sam Alexander)",
    intelligence: "6/7",
    strength: "6/7",
    speed: "7/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "3/7",
    image: "nova.webp",
  },
  {
    title: "Quicksilver (Pietro Maximoff)",
    intelligence: "3/7",
    strength: "4/7",
    speed: "5/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "quicksilver.webp",
  },
  {
    title: "War Machine (Jim Rhodes)",
    intelligence: "3/7",
    strength: "6/7",
    speed: "5/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "war-machine.webp",
  },
  {
    title: "Drax the Destroyer",
    intelligence: "2/7",
    strength: "5/7",
    speed: "2/7",
    durability: "7/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "drax-the-destroyer.webp",
  },
  {
    title: "Gamora",
    intelligence: "3/7",
    strength: "3/7",
    speed: "4/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "gamora.webp",
  },
  {
    title: "Iceman (Bobby Drake)",
    intelligence: "2/7",
    strength: "3/7",
    speed: "3/7",
    durability: "4/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "iceman.webp",
  },
  {
    title: "Wasp (Janet Van Dyne)",
    intelligence: "3/7",
    strength: "5/7",
    speed: "3/7",
    durability: "2/7",
    energy: "4/7",
    fighting_skills: "4/7",
    image: "wasp.webp",
  },
  {
    title: "Beast (Hank McCoy)",
    intelligence: "5/7",
    strength: "4/7",
    speed: "3/7",
    durability: "4/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "beast.webp",
  },
  {
    title: "Captain America (Sam Wilson)",
    intelligence: "2/7",
    strength: "2/7",
    speed: "3/7",
    durability: "2/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "captain-america-sam-wilson.webp",
  },
  {
    title: "Ghost-Spider (Gwen Stacy)",
    intelligence: "3/7",
    strength: "4/7",
    speed: "3/7",
    durability: "3/7",
    energy: "1/7",
    fighting_skills: "3/7",
    image: "ghost-spider.webp",
  },
  {
    title: "Talon (Laura Kinney)",
    intelligence: "2/7",
    strength: "2/7",
    speed: "3/7",
    durability: "4/7",
    energy: "1/7",
    fighting_skills: "6/7",
    image: "talon.webp",
  },
  {
    title: "Psylocke (Betsy Braddock)",
    intelligence: "2/7",
    strength: "6/7",
    speed: "4/7",
    durability: "6/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "psylocke.webp",
  },
  {
    title: "Cyclops (Scott Summers)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "2/7",
    durability: "2/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "cyclops.webp",
  },
  {
    title: "She-Hulk (Jennifer Walters)",
    intelligence: "3/7",
    strength: "7/7",
    speed: "3/7",
    durability: "6/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "she-hulk.webp",
  },
  {
    title: "Invisible Woman (Sue Richards)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "3/7",
    durability: "6/7",
    energy: "5/7",
    fighting_skills: "3/7",
    image: "invisible-woman.webp",
  },
  {
    title: "Mister Fantastic (Reed Richards)",
    intelligence: "6/7",
    strength: "2/7",
    speed: "2/7",
    durability: "5/7",
    energy: "1/7",
    fighting_skills: "3/7",
    image: "mister-fantastic.webp",
  },
  {
    title: "Spider-Man 2099 (Miguel O'Hara)",
    intelligence: "4/7",
    strength: "4/7",
    speed: "4/7",
    durability: "3/7",
    energy: "2/7",
    fighting_skills: "2/7",
    image: "spider-man-2099.webp",
  },
  {
    title: "Luke Cage (Carl Lucas)",
    intelligence: "3/7",
    strength: "4/7",
    speed: "2/7",
    durability: "5/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "luke-cage.webp",
  },
  {
    title: "Iron Fist (Danny Rand)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "2/7",
    durability: "3/7",
    energy: "3/7",
    fighting_skills: "6/7",
    image: "iron-fist.webp",
  },
  {
    title: "Adam Warlock",
    intelligence: "3/7",
    strength: "5/7",
    speed: "7/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "2/7",
    image: "adam-warlock.webp",
  },
  {
    title: "Black Bolt (Blackagar Boltagon)",
    intelligence: "2/7",
    strength: "5/7",
    speed: "3/7",
    durability: "3/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "black-bolt.webp",
  },
  {
    title: "Rogue (Anna Marie LeBeau)",
    intelligence: "7/7",
    strength: "7/7",
    speed: "7/7",
    durability: "7/7",
    energy: "7/7",
    fighting_skills: "7/7",
    image: "rogue.webp",
  },
  {
    title: "Domino (Neena Thurman)",
    intelligence: "2/7",
    strength: "2/7",
    speed: "2/7",
    durability: "2/7",
    energy: "3/7",
    fighting_skills: "6/7",
    image: "domino.webp",
  },
  {
    title: "Spider-Woman (Jessica Drew)",
    intelligence: "3/7",
    strength: "5/7",
    speed: "3/7",
    durability: "4/7",
    energy: "5/7",
    fighting_skills: "4/7",
    image: "spider-woman.webp",
  },
  {
    title: "Nebula",
    intelligence: "4/7",
    strength: "5/7",
    speed: "2/7",
    durability: "3/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "nebula.webp",
  },
  {
    title: "Ms. Marvel (Kamala Khan)",
    intelligence: "2/7",
    strength: "4/7",
    speed: "3/7",
    durability: "4/7",
    energy: "1/7",
    fighting_skills: "2/7",
    image: "ms-marvel.webp",
  },
  {
    title: "Mantis",
    intelligence: "3/7",
    strength: "3/7",
    speed: "7/7",
    durability: "7/7",
    energy: "3/7",
    fighting_skills: "6/7",
    image: "mantis.webp",
  },
  {
    title: "Jessica Jones",
    intelligence: "2/7",
    strength: "4/7",
    speed: "3/7",
    durability: "4/7",
    energy: "1/7",
    fighting_skills: "3/7",
    image: "jessica-jones.webp",
  },
  {
    title: "Angel (Warren Worthington III)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "3/7",
    durability: "2/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "angel.webp",
  },
  {
    title: "Doctor Doom (Victor Von Doom)",
    intelligence: "6/7",
    strength: "4/7",
    speed: "5/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "doctor-doom.webp",
  },
  {
    title: "Juggernaut (Cain Marko)",
    intelligence: "2/7",
    strength: "7/7",
    speed: "2/7",
    durability: "7/7",
    energy: "1/7",
    fighting_skills: "4/7",
    image: "juggernaut.webp",
  },
  {
    title: "Magneto (Max Eisenhardt)",
    intelligence: "5/7",
    strength: "2/7",
    speed: "5/7",
    durability: "2/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "magneto.webp",
  },
  {
    title: "White Queen (Emma Frost)",
    intelligence: "4/7",
    strength: "4/7",
    speed: "2/7",
    durability: "5/7",
    energy: "5/7",
    fighting_skills: "3/7",
    image: "white-queen.webp",
  },
  {
    title: "Shang-Chi",
    intelligence: "4/7",
    strength: "3/7",
    speed: "4/7",
    durability: "4/7",
    energy: "3/7",
    fighting_skills: "7/7",
    image: "shang-chi.webp",
  },
  {
    title: "Loki",
    intelligence: "5/7",
    strength: "5/7",
    speed: "7/7",
    durability: "6/7",
    energy: "6/7",
    fighting_skills: "3/7",
    image: "loki.webp",
  },
  {
    title: "Photon (Monica Rambeau)",
    intelligence: "3/7",
    strength: "2/7",
    speed: "6/7",
    durability: "4/7",
    energy: "6/7",
    fighting_skills: "4/7",
    image: "photon.webp",
  },
  {
    title: "Black Widow (Yelena Belova)",
    intelligence: "3/7",
    strength: "6/7",
    speed: "5/7",
    durability: "7/7",
    energy: "6/7",
    fighting_skills: "5/7",
    image: "black-widow-yelena-belova.webp",
  },
];
const seedCharacters = async () => {
  await Characters.sync();
  await Characters.bulkCreate(charactersData);
};

module.exports = seedCharacters;
